= Lottie file and animation format
:jbake-type: page
:jbake-description: Information about the Lottie file and animation format
:jbake-priority: 1.0
:showtitle:

== What are Lottie files?

As described on https://lottiefiles.com/what-is-lottie[lottiefiles.com/what-is-lottie^]:

**_A Lottie is a JSON-based animation file format that allows you to ship animations on any platform as easily as shipping static assets. They are small files that work on any device and can scale up or down without pixelation. LottieFiles lets you create, edit, test, collaborate on and ship a Lottie in the easiest way possible._**

Developer info is provided on https://lottiefiles.github.io/lottie-docs/Introduction/[lottiefiles.github.io/lottie-docs^] with clear info about the data model, how animations are defined, etc.

The structure of an animation is described on https://lottiefiles.github.io/lottie-docs/breakdown/bouncy_ball/[lottiefiles.github.io/lottie-docs/breakdown/bouncy_ball^].

=== Lottie file format

Two formats are used:

. Json files that define animations:
** The top level object https://lottiefiles.github.io/lottie-docs/animation/[Animation^] is described here with click-through to all possible child data.
** The full schema is available on https://lottiefiles.github.io/lottie-docs/schema/lottie.schema.json
. dotLottie: ZIP based including one or more json, manifext and other related files, see https://dotlottie.io/structure/#dotlottie-structure[the structure as described in the official documentation^].

=== Creating Lottie animations

* LottieFiles is working on an editor "Lottie Creator", you can https://lottiefiles.com/lottie-creator[join the waiting list^].
* https://createwithflow.com/[Flow has a free animation tool^], but to be able to export to LottieFiles, you need a licensed version, starting from 99$/year. *The test files and animations for the Lottie4J project are created with a free education version that was provided by Flow, thanks!*
* https://www.haikuanimator.com/[Haiku^], a project that became
into https://www.haikuanimator.com/blog/open-source[opensource in August 2021^].
* https://www.fable.app/[Fable^] is an animation tool that can export as Lottie.
* Adobe AfterEffects is probably used the most to create Lottie animations, but this is expensive software. On top of that, Adobe should be used with care (*).

(*): this is a personal note... one day I was a heavy user of all Adobe software. Flash (by FutureSplash, acquired by Macromedia, acquired by Adobe) was my introduction into multimedia and I learned a lot by using it, even for business applications with Flex. But since that time, many years ago, Adobe turned into an evil company. From personal experience and what people share online, you need to be aware they have both a https://www.reddit.com/r/assholedesign/comments/10946en/forgot_to_cancel_my_free_trial_for_adobe_now_they/[bad reputation for how difficult it can be to cancel a (trial) subscription^], and https://www.quora.com/Is-Adobe-spying-on-you-with-their-software?share=1[their software should be handled as spyware^]. There are extremely good alternatives, which are free or cheaper. For instance, instead of Photoshop, try the online https://www.photopea.com/[Photopea^].
